import './globals.css';
import Navbar from '../components/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-[#f2f2f2]">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
